### ISSUE TITLE
Valency validation: entity type valency can never be empty, at least the explicit value "empty" needs to be there

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1939]
Entity type valency needs to be always declared. I.e. the following situation should generate the validation warning "Missing entity type valency - Actant 2"
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/8da40919-541c-45d8-907d-57382a1a01db)
This then, by necessity, will also be there upon creation of a new Action, this cannot be avoided, but it is fine.

**Comment by adammertel** [comment]
I have added a new warning type to the [doc](https://docs.google.com/document/d/1pmsCjNLHAOA58gVrwV64Qfsp-9wO4kZoXbtyjViMuQA/edit).

![image](https://github.com/DISSINET/InkVisitor/assets/12932677/fabef8f6-386d-4c2c-926a-d8a01c025982)

**Comment by davidzbiral** [comment]
@adammertel Sounds good, you can probably close, if also solved in the GUI?

**Comment by adammertel** [comment]
No, it's not solved yet, we just need to split in more steps :)
